#!/usr/bin/env bash
# Initialize a fresh SpecFlow v3.1 project from this template.
set -euo pipefail

echo "=== SpecFlow v3.1 Project Setup ==="
echo ""

# Prompt for project name
read -rp "Project name: " NAME
NAME="${NAME:-My Project}"

# Prompt for tech stack
echo ""
echo "Select your tech stack:"
echo "  1) Python (pytest, ruff, black)"
echo "  2) Node.js / TypeScript (vitest, eslint, prettier)"
echo "  3) Go (go test, golangci-lint, gofmt)"
echo "  4) Other (you'll configure the quality-gate hook manually)"
read -rp "Choice [1-4]: " STACK_CHOICE
STACK_CHOICE="${STACK_CHOICE:-4}"

case "$STACK_CHOICE" in
  1)
    STACK="python"
    TEST_CMD="python -m pytest tests/ -v"
    LINT_CMD="python -m ruff check src/ tests/"
    FMT_CMD="python -m black --check src/ tests/"
    ;;
  2)
    STACK="node"
    TEST_CMD="npx vitest run"
    LINT_CMD="npx eslint src/ tests/"
    FMT_CMD="npx prettier --check 'src/**/*.{ts,tsx}' 'tests/**/*.{ts,tsx}'"
    ;;
  3)
    STACK="go"
    TEST_CMD="go test ./..."
    LINT_CMD="golangci-lint run"
    FMT_CMD="test -z \$(gofmt -l .)"
    ;;
  *)
    STACK="other"
    TEST_CMD="echo 'TODO: configure test command' && exit 1"
    LINT_CMD="echo 'TODO: configure lint command' && exit 1"
    FMT_CMD="echo 'TODO: configure format command' && exit 1"
    ;;
esac

echo ""
echo "Initializing '$NAME' with $STACK stack..."

# Create the full v3.1 directory structure — every directory the 10-phase
# pipeline writes artifacts to.
mkdir -p docs/specs docs/plans docs/reviews docs/dashboard
mkdir -p docs/adr docs/architecture docs/security docs/releases docs/retrospectives
mkdir -p src src/contracts tests/unit tests/integration tests/e2e tests/data
mkdir -p tests/governance
mkdir -p verification
mkdir -p .github/workflows .github/ISSUE_TEMPLATE
mkdir -p .claude/rules .claude/skills/verifier .claude/skills/doc-render
mkdir -p schemas templates scripts

# Record the stack — scripts/run-quality-gates.sh and the RELEASE hook
# (scripts/release-$(cat .stack).sh) both key on this file.
echo "$STACK" > .stack
echo "Wrote .stack = $STACK"

# Generate the per-stack quality-gate hook that run-quality-gates.sh invokes.
HOOK="scripts/quality-gates-${STACK}.sh"
if [ ! -f "$HOOK" ]; then
  cat > "$HOOK" <<HOOK_EOF
#!/usr/bin/env bash
# Per-stack quality gates for ${STACK} — invoked by scripts/run-quality-gates.sh.
# Generated by init-project.sh; edit freely.
set -euo pipefail

echo "--- lint ---"
${LINT_CMD}
echo "--- format check ---"
${FMT_CMD}
echo "--- tests ---"
${TEST_CMD}
HOOK_EOF
  chmod +x "$HOOK"
  echo "Created $HOOK"
fi

# Copy IDEA.md template
if [ ! -f IDEA.md ]; then
  cp templates/IDEA.md IDEA.md
  echo "Created IDEA.md — fill it in before running /superpowers:brainstorming"
fi

# Escape sed replacement metacharacters (& \ /)
escape_sed() { printf '%s' "$1" | sed 's/[&/\]/\\&/g'; }

# Substitute project name in CLAUDE.md
if [ -f CLAUDE.md ]; then
  SAFE_NAME=$(escape_sed "$NAME")
  SAFE_STACK=$(escape_sed "$STACK")
  sed -i.bak "s/{{PROJECT_NAME}}/$SAFE_NAME/g; s/{{STACK}}/$SAFE_STACK/g" CLAUDE.md && rm -f CLAUDE.md.bak
fi

# Initialize git
if [ ! -d .git ]; then
  git init -b main
  git add -A
  git commit -m "chore: initialize $NAME from SpecFlow v3.1 template"
fi

# Create phase/spec branch
git checkout -b phase/spec 2>/dev/null || git checkout phase/spec

echo ""
echo "=== Setup Complete ==="
echo ""
echo "You are now on branch 'phase/spec'. The 10-phase pipeline:"
echo "  BRAINSTORM+SPECIFY (phase/spec) -> ARCHITECTURE (phase/arch) ->"
echo "  PLAN+TASKS+ANALYZE (phase/plan) -> IMPLEMENT (impl/plan-N-*) ->"
echo "  VALIDATE -> SECURITY -> RELEASE"
echo ""
echo "Next steps:"
echo "  1) Edit IDEA.md with your product idea"
echo "  2) Run /superpowers:brainstorming to explore the design"
echo "  3) Run /speckit.specify to formalize the spec"
echo "  4) Tag critical requirements [verifiable] or [verifiable-model]"
echo "  5) Push and open a PR to main, then continue with phase/arch"
echo ""
echo "Notes:"
echo "  - This template ships a demo pipeline (docs/specs/2026-05-28-demo-greeting-*)."
echo "    Its Dafny proofs make 'dafny' required by run-quality-gates.sh — install"
echo "    Dafny, or remove the demo artifacts if you don't need the example."
echo "  - Verifier reviews run on your Claude subscription: scripts/run-verifier.sh <PR>"
echo "    from a terminal OUTSIDE any Claude Code session."
echo "  - See verification/README.md for the Dafny proof-writing guide."
echo "  - After pushing to GitHub, run: bash scripts/configure-repo.sh"
