#!/usr/bin/env bash
# Per-stack quality gates for .NET/C# — invoked by scripts/run-quality-gates.sh.
# Generated by init-project.sh as "other"; hand-edited for dotnet.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if ! find . -maxdepth 3 -name '*.csproj' -not -path './bin/*' -not -path './obj/*' | grep -q .; then
  echo "SKIP dotnet gates (no .csproj found yet)"
  exit 0
fi

echo "--- format check ---"
dotnet format --verify-no-changes

echo "--- build ---"
dotnet build --configuration Release

echo "--- tests ---"
dotnet test --configuration Release --no-build
